# Generated by Django 5.2.1 on 2025-06-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('todos', models.JSONField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('level', models.IntegerField(choices=[(0, 'Top 0'), (1, 'Top 1'), (2, 'Top 2'), (3, 'Top 3')], default=3)),
                ('tags', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('relive', models.CharField(max_length=20)),
                ('skip', models.CharField(max_length=20)),
                ('finish_info', models.TextField()),
            ],
        ),
    ]
