# Generated by Django 5.2.1 on 2025-06-06 08:01

import daily_todos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(default=daily_todos.models.gen_default_datetodos_key, max_length=80, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('todos', models.JSONField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(default=daily_todos.models.gen_default_livetodo_key, max_length=80, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('level', models.IntegerField(choices=[(0, 'Top 0'), (1, 'Top 1'), (2, 'Top 2'), (3, 'Top 3')], default=3)),
                ('tags', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('relive', models.CharField(help_text='N d/w/m/y; weekday; workday;', max_length=20)),
                ('skip', models.CharField(help_text='on Mon.; on Tue.; on Wed.; on Thu.; on Fri; on Sat.; on Sun.;<br/>on */*/5; <br/> weekend; day off;', max_length=20)),
                ('finish_info', models.TextField(help_text='[]<br/>() (p30) (p31/p32)<br/>{} {N} {p30/ p31/ p32/ p33} {1,2,1,1} {N;+5%,-4,-50%}')),
            ],
        ),
        migrations.CreateModel(
            name='TodoSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('submitted_time', models.DateTimeField()),
                ('date_todos', models.JSONField()),
                ('live_todos', models.JSONField()),
            ],
        ),
    ]
