# Generated by Django 5.2.1 on 2025-06-05 05:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livetodo',
            name='uuid',
        ),
        migrations.AddField(
            model_name='livetodo',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=300),
        ),
        migrations.AlterField(
            model_name='livetodo',
            name='finish_info',
            field=models.TextField(help_text='[]<br/>() (p30) (p31/p32)<br/>{} {N} {p30/ p31/ p32/ p33} {1,2,1,1} {N;+5%,-4,-50%}'),
        ),
        migrations.AlterField(
            model_name='livetodo',
            name='relive',
            field=models.CharField(help_text='N d/w/m/y; weekday; workday;', max_length=20),
        ),
        migrations.AlterField(
            model_name='livetodo',
            name='skip',
            field=models.CharField(help_text='on Mon.; on Tue.; on Wed.; on Thu.; on Fri; on Sat.; on Sun.;<br/>on */*/5; <br/> weekend; day off;', max_length=20),
        ),
    ]
