# Generated by Django 5.2.1 on 2025-06-05 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_todos', '0002_remove_livetodo_uuid_livetodo_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetodos',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='livetodo',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=80, unique=True),
        ),
    ]
