# Generated by Django 5.2.1 on 2025-06-05 16:12

import daily_todos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_todos', '0004_todosubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetodos',
            name='key',
            field=models.CharField(default=daily_todos.models.gen_default_datetodos_key, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='livetodo',
            name='key',
            field=models.CharField(default=daily_todos.models.gen_default_livetodo_key, max_length=80, unique=True),
        ),
    ]
