# Generated by Django 5.2.1 on 2025-06-06 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLongTermToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='自动生成的唯一令牌', max_length=64, unique=True, verbose_name='Token值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(blank=True, help_text='可选：设置后Token将在此时效后失效', null=True, verbose_name='过期时间')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '管理员长期Token',
                'verbose_name_plural': '管理员长期Tokens',
            },
        ),
    ]
